# Generated by Django 5.1.6 on 2025-02-23 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('gas_leak', 'Gas Leak'), ('meter_issue', 'Meter Issue'), ('billing', 'Billing Issue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
